project:
  type: website
  output-dir: docs

website:
  title: "Munich Bicycle Counter Patterns"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Proposal

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true

execute:
  warning: false
  message: false
